### New car model
POST localhost:8080/api/car/models/add
Content-Type: application/json

{
  "name": "Kamaz-4326",
  "type": "HEAVY",
  "annualLimit": 40000.0,
  "fuelNorm": 32.0,
  "fuel": 4
}

### Car models
GET localhost:8080/api/car/models/all

