### New car
POST http://localhost:8080/api/cars/add
Content-Type: application/json

{
  "plateNumber": "01K426AA",
  "tankCapacity": 300.0,
  "odometerStartYear": 50000,
  "odometerCurrent": 50000,
  "fuelSpentYtd": 0.0,
  "driver": 4,
  "carModel": 4
}


### Cars
GET http://localhost:8080/api/cars/all
