### New car
POST http://localhost:8080/api/cars/add
Content-Type: application/json

{
  "plateNumber": "01A999AA",
  "odometerStartYear": 17400,
  "odometerCurrent": 120000,
  "fuelSpentYtd": 0.0,
  "driver": {"id": 1},
  "carModel": {"id": 1},
  "fuel": {"id": 1}
}
