### New driver
POST http://localhost:8080/api/drivers/add
Content-Type: application/json

{
  "firstName": "Dilshod",
  "lastName": "Valijonov",
  "phoneNumber": "+998978895563",
  "licenseNumber": "AA159916"
}

### All drivers
GET http://localhost:8080/api/drivers/all